version: '3'

services:
  app:
    build: .
    container_name: time-management-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json
    environment:
      - NODE_ENV=production

  # Uncomment to use PostgreSQL instead of SQLite
  # db:
  #   image: postgres:14-alpine
  #   container_name: time-management-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: timemanagement
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# Uncomment to use PostgreSQL
# volumes:
#   postgres-data:
